# mySql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyproject?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "0000"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.sport_test
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9000


